[2022-08-28 13:50:40,649] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file scheduled__2022-08-27T00:00:00+00:00 [queued]>
[2022-08-28 13:50:40,792] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file scheduled__2022-08-27T00:00:00+00:00 [queued]>
[2022-08-28 13:50:40,798] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 13:50:40,801] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-28 13:50:40,803] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 20:19:30,869] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_run_file> on 2022-08-27 00:00:00+00:00
[2022-08-28 20:19:47,784] {standard_task_runner.py:52} INFO - Started process 28777 to run task
[2022-08-28 20:19:48,262] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'waiting_for_run_file', 'scheduled__2022-08-27T00:00:00+00:00', '--job-id', '3317', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmp6ggsy8mu', '--error-file', '/tmp/tmp7b5yfrzd']
[2022-08-28 20:19:48,303] {standard_task_runner.py:80} INFO - Job 3317: Subtask waiting_for_run_file
[2022-08-28 20:19:52,019] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.waiting_for_run_file scheduled__2022-08-27T00:00:00+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-28 20:19:57,563] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=waiting_for_run_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-27T00:00:00+00:00
[2022-08-28 20:19:57,692] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-28 20:19:57,695] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:47:06,637] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-08-29 03:47:06,695] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 28777. PIDs of all processes in the group: [28777]
[2022-08-29 03:47:06,702] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 28777
[2022-08-29 03:47:06,708] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-08-29 03:47:06,856] {process_utils.py:75} INFO - Process psutil.Process(pid=28777, status='terminated', exitcode=0, started='20:19:47') (28777) terminated with exit code 0
