[2022-08-29 03:47:09,186] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file scheduled__2022-08-28T00:00:00+00:00 [queued]>
[2022-08-29 03:47:09,215] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file scheduled__2022-08-28T00:00:00+00:00 [queued]>
[2022-08-29 03:47:09,217] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 03:47:09,218] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-29 03:47:09,219] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 03:47:09,262] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_run_file> on 2022-08-28 00:00:00+00:00
[2022-08-29 03:47:09,273] {standard_task_runner.py:52} INFO - Started process 28786 to run task
[2022-08-29 03:47:09,297] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'waiting_for_run_file', 'scheduled__2022-08-28T00:00:00+00:00', '--job-id', '3318', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpqynw0qa9', '--error-file', '/tmp/tmptsvlu3ew']
[2022-08-29 03:47:09,298] {standard_task_runner.py:80} INFO - Job 3318: Subtask waiting_for_run_file
[2022-08-29 03:47:09,573] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.waiting_for_run_file scheduled__2022-08-28T00:00:00+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-29 03:47:10,079] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=waiting_for_run_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-28T00:00:00+00:00
[2022-08-29 03:47:10,116] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:47:10,117] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:47:20,141] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:47:20,143] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:47:30,155] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:47:30,157] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:47:40,155] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:47:40,156] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:47:50,174] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:47:50,175] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:48:00,200] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:48:00,202] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:48:08,826] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:48:08,828] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:48:18,847] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:48:18,848] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:48:28,877] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:48:28,879] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:48:38,856] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:48:38,857] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:48:48,881] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-29 03:48:48,883] {filesystem.py:58} INFO - Poking for file /opt/***/dags/test.txt
[2022-08-29 03:48:48,886] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: trigger_sensor
[2022-08-29 03:48:48,899] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=trigger_sensor, task_id=waiting_for_run_file, execution_date=20220828T000000, start_date=20220829T034709, end_date=20220829T034848
[2022-08-29 03:48:48,918] {standard_task_runner.py:97} ERROR - Failed to execute job 3318 for task waiting_for_run_file (Snap. Time is OUT. DAG id: trigger_sensor; 28786)
[2022-08-29 03:48:48,971] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-29 03:48:49,030] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
