[2022-09-06 16:28:01,015] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tables_name_1.check_table_exist manual__2022-09-06T16:27:57.753894+00:00 [queued]>
[2022-09-06 16:28:01,028] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tables_name_1.check_table_exist manual__2022-09-06T16:27:57.753894+00:00 [queued]>
[2022-09-06 16:28:01,029] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-06 16:28:01,030] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-06 16:28:01,031] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-06 16:28:01,052] {taskinstance.py:1397} INFO - Executing <Task(BranchPythonOperator): check_table_exist> on 2022-09-06 16:27:57.753894+00:00
[2022-09-06 16:28:01,060] {standard_task_runner.py:52} INFO - Started process 6850 to run task
[2022-09-06 16:28:01,065] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tables_name_1', 'check_table_exist', 'manual__2022-09-06T16:27:57.753894+00:00', '--job-id', '3853', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmp73fa6oym', '--error-file', '/tmp/tmp3jpzv7br']
[2022-09-06 16:28:01,066] {standard_task_runner.py:80} INFO - Job 3853: Subtask check_table_exist
[2022-09-06 16:28:01,151] {task_command.py:371} INFO - Running <TaskInstance: tables_name_1.check_table_exist manual__2022-09-06T16:27:57.753894+00:00 [running]> on host eba23da77ca5
[2022-09-06 16:28:01,247] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tables_name_1
AIRFLOW_CTX_TASK_ID=check_table_exist
AIRFLOW_CTX_EXECUTION_DATE=2022-09-06T16:27:57.753894+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-06T16:27:57.753894+00:00
[2022-09-06 16:28:01,264] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-09-06 16:28:01,277] {jobs_dag.py:44} INFO - THIS IS THE SCHEMA:
[2022-09-06 16:28:01,281] {jobs_dag.py:45} INFO - pg_catalog
[2022-09-06 16:28:01,290] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-09-06 16:28:01,302] {logging_mixin.py:115} INFO - None
[2022-09-06 16:28:01,303] {python.py:173} INFO - Done. Returned value was: create_table
[2022-09-06 16:28:01,303] {skipmixin.py:140} INFO - Following branch create_table
[2022-09-06 16:28:01,304] {skipmixin.py:175} INFO - Skipping tasks []
[2022-09-06 16:28:01,362] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tables_name_1, task_id=check_table_exist, execution_date=20220906T162757, start_date=20220906T162801, end_date=20220906T162801
[2022-09-06 16:28:01,398] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06 16:28:01,469] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
