[2022-08-26 16:41:11,625] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:41:10.685029+00:00 [queued]>
[2022-08-26 16:41:11,639] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:41:10.685029+00:00 [queued]>
[2022-08-26 16:41:11,640] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-26 16:41:11,641] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-26 16:41:11,642] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-26 16:41:11,662] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_run_file> on 2022-08-26 16:41:10.685029+00:00
[2022-08-26 16:41:11,672] {standard_task_runner.py:52} INFO - Started process 19447 to run task
[2022-08-26 16:41:11,677] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'waiting_for_run_file', 'manual__2022-08-26T16:41:10.685029+00:00', '--job-id', '3278', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpz209rrt0', '--error-file', '/tmp/tmpmscuuawh']
[2022-08-26 16:41:11,678] {standard_task_runner.py:80} INFO - Job 3278: Subtask waiting_for_run_file
[2022-08-26 16:41:11,765] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:41:10.685029+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-26 16:41:11,862] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=waiting_for_run_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-26T16:41:10.685029+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-26T16:41:10.685029+00:00
[2022-08-26 16:41:11,874] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:41:11,875] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:41:21,876] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:41:21,878] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:41:31,893] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:41:31,894] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:41:41,914] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:41:41,916] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:41:51,905] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:41:51,907] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:42:01,919] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:42:01,921] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:42:11,939] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:42:11,940] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:42:21,943] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:42:21,944] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:42:31,962] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:42:31,964] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:42:41,985] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:42:41,986] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:42:51,983] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:42:51,984] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:42:51,985] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: trigger_sensor
[2022-08-26 16:42:52,002] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=trigger_sensor, task_id=waiting_for_run_file, execution_date=20220826T164110, start_date=20220826T164111, end_date=20220826T164252
[2022-08-26 16:42:52,021] {standard_task_runner.py:97} ERROR - Failed to execute job 3278 for task waiting_for_run_file (Snap. Time is OUT. DAG id: trigger_sensor; 19447)
[2022-08-26 16:42:52,052] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-26 16:42:52,109] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
