[2022-09-02 21:53:50,983] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.process_results.remove_file manual__2022-09-02T21:53:03.149821+00:00 [queued]>
[2022-09-02 21:53:50,995] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.process_results.remove_file manual__2022-09-02T21:53:03.149821+00:00 [queued]>
[2022-09-02 21:53:50,996] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 21:53:50,996] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-02 21:53:50,997] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 21:53:51,016] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): process_results.remove_file> on 2022-09-02 21:53:03.149821+00:00
[2022-09-02 21:53:51,022] {standard_task_runner.py:52} INFO - Started process 444 to run task
[2022-09-02 21:53:51,026] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'process_results.remove_file', 'manual__2022-09-02T21:53:03.149821+00:00', '--job-id', '3788', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpec_nw958', '--error-file', '/tmp/tmp9d6ol128']
[2022-09-02 21:53:51,027] {standard_task_runner.py:80} INFO - Job 3788: Subtask process_results.remove_file
[2022-09-02 21:53:51,124] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.process_results.remove_file manual__2022-09-02T21:53:03.149821+00:00 [running]> on host 643b3d669374
[2022-09-02 21:53:51,232] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=process_results.remove_file
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T21:53:03.149821+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-02T21:53:03.149821+00:00
[2022-09-02 21:53:51,234] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-02 21:53:51,235] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm /opt/***/dags/test.txt']
[2022-09-02 21:53:51,252] {subprocess.py:85} INFO - Output:
[2022-09-02 21:53:51,259] {subprocess.py:92} INFO - rm: cannot remove '/opt/***/dags/test.txt': No such file or directory
[2022-09-02 21:53:51,259] {subprocess.py:96} INFO - Command exited with return code 1
[2022-09-02 21:53:51,279] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-09-02 21:53:51,286] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=trigger_sensor, task_id=process_results.remove_file, execution_date=20220902T215303, start_date=20220902T215350, end_date=20220902T215351
[2022-09-02 21:53:51,306] {standard_task_runner.py:97} ERROR - Failed to execute job 3788 for task process_results.remove_file (Bash command failed. The command returned a non-zero exit code 1.; 444)
[2022-09-02 21:53:51,360] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-02 21:53:51,424] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
