[2022-08-26 19:22:14,104] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.bash_task manual__2022-08-26T19:22:09.941556+00:00 [queued]>
[2022-08-26 19:22:14,118] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.bash_task manual__2022-08-26T19:22:09.941556+00:00 [queued]>
[2022-08-26 19:22:14,118] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-26 19:22:14,119] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-26 19:22:14,120] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-26 19:22:14,159] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): bash_task> on 2022-08-26 19:22:09.941556+00:00
[2022-08-26 19:22:14,168] {standard_task_runner.py:52} INFO - Started process 22990 to run task
[2022-08-26 19:22:14,174] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'bash_task', 'manual__2022-08-26T19:22:09.941556+00:00', '--job-id', '3284', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpds2u1ko1', '--error-file', '/tmp/tmpl_6487i6']
[2022-08-26 19:22:14,175] {standard_task_runner.py:80} INFO - Job 3284: Subtask bash_task
[2022-08-26 19:22:14,275] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.bash_task manual__2022-08-26T19:22:09.941556+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-26 19:22:14,388] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-26T19:22:09.941556+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-26T19:22:09.941556+00:00
[2022-08-26 19:22:14,391] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-26 19:22:14,394] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm text.txt']
[2022-08-26 19:22:14,413] {subprocess.py:85} INFO - Output:
[2022-08-26 19:22:14,424] {subprocess.py:92} INFO - rm: cannot remove 'text.txt': No such file or directory
[2022-08-26 19:22:14,425] {subprocess.py:96} INFO - Command exited with return code 1
[2022-08-26 19:22:14,451] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-26 19:22:14,457] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=trigger_sensor, task_id=bash_task, execution_date=20220826T192209, start_date=20220826T192214, end_date=20220826T192214
[2022-08-26 19:22:14,478] {standard_task_runner.py:97} ERROR - Failed to execute job 3284 for task bash_task (Bash command failed. The command returned a non-zero exit code 1.; 22990)
[2022-08-26 19:22:14,509] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-26 19:22:14,558] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
